[project]
name = "ttseval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ipython>=8.37.0",
    "jupyterlab>=4.4.3",
    "nltk>=3.9.1",
]
